// <auto-generated />
namespace AgiliFood.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class remocao_funcionario : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(remocao_funcionario));
        
        string IMigrationMetadata.Id
        {
            get { return "201905050306332_remocao_funcionario"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
