// <auto-generated />
namespace AgiliFood.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class drop_coluna_dataCadastro : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(drop_coluna_dataCadastro));
        
        string IMigrationMetadata.Id
        {
            get { return "201904260155532_drop_coluna_dataCadastro"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
