// <auto-generated />
namespace AgiliFood.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class drp_usuariomodel : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(drp_usuariomodel));
        
        string IMigrationMetadata.Id
        {
            get { return "201904260136018_drp_usuariomodel"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
